/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tetris.app;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JColorChooser;
import javax.swing.event.ChangeEvent;
import tetris.lib.definitions.ChosenColor;

/**
 *
 * @author Bea⚝
 */
public class Cores extends javax.swing.JFrame implements ActionListener {

    /**
     * Creates new form Cores
     */
    Color chosenColorPieceI = null;
    Color chosenColorPieceJ = null;
    Color chosenColorPieceL = null;
    Color chosenColorPieceT = null;
    Color chosenColorPieceO = null;
    Color chosenColorPieceS = null;
    Color chosenColorPieceZ = null;

    public ChosenColor colors = new ChosenColor(chosenColorPieceI,
            chosenColorPieceJ, chosenColorPieceO, chosenColorPieceS,
            chosenColorPieceL, chosenColorPieceZ, chosenColorPieceT);

    public Cores() {
        initComponents();
        btChooseColorI.addActionListener(this);
        btChooseColorJ.addActionListener(this);
        btChooseColorL.addActionListener(this);
        btChooseColorT.addActionListener(this);
        btChooseColorO.addActionListener(this);
        btChooseColorS.addActionListener(this);
        btChooseColorZ.addActionListener(this);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btChooseColorI = new javax.swing.JButton();
        btChooseColorJ = new javax.swing.JButton();
        btChooseColorL = new javax.swing.JButton();
        btChooseColorO = new javax.swing.JButton();
        btChooseColorT = new javax.swing.JButton();
        btChooseColorS = new javax.swing.JButton();
        btChooseColorZ = new javax.swing.JButton();
        btJogar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new java.awt.GridLayout(3, 0));

        btChooseColorI.setText("Escolher cor da peça I");
        btChooseColorI.setMaximumSize(new java.awt.Dimension(25, 23));
        btChooseColorI.setMinimumSize(new java.awt.Dimension(25, 23));
        btChooseColorI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btChooseColorIActionPerformed(evt);
            }
        });
        getContentPane().add(btChooseColorI);

        btChooseColorJ.setText("Escolher cor da peça J");
        btChooseColorJ.setMaximumSize(new java.awt.Dimension(25, 23));
        btChooseColorJ.setMinimumSize(new java.awt.Dimension(25, 23));
        btChooseColorJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btChooseColorJActionPerformed(evt);
            }
        });
        getContentPane().add(btChooseColorJ);

        btChooseColorL.setText("Escolher cor da peça L");
        btChooseColorL.setMaximumSize(new java.awt.Dimension(25, 23));
        btChooseColorL.setMinimumSize(new java.awt.Dimension(25, 23));
        btChooseColorL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btChooseColorLActionPerformed(evt);
            }
        });
        getContentPane().add(btChooseColorL);

        btChooseColorO.setText("Escolher cor da peça O");
        btChooseColorO.setMaximumSize(new java.awt.Dimension(25, 23));
        btChooseColorO.setMinimumSize(new java.awt.Dimension(25, 23));
        btChooseColorO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btChooseColorOActionPerformed(evt);
            }
        });
        getContentPane().add(btChooseColorO);

        btChooseColorT.setText("Escolher cor da peça T");
        btChooseColorT.setMaximumSize(new java.awt.Dimension(25, 23));
        btChooseColorT.setMinimumSize(new java.awt.Dimension(25, 23));
        btChooseColorT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btChooseColorTActionPerformed(evt);
            }
        });
        getContentPane().add(btChooseColorT);

        btChooseColorS.setText("Escolher cor da peça S");
        btChooseColorS.setMaximumSize(new java.awt.Dimension(25, 23));
        btChooseColorS.setMinimumSize(new java.awt.Dimension(25, 23));
        btChooseColorS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btChooseColorSActionPerformed(evt);
            }
        });
        getContentPane().add(btChooseColorS);

        btChooseColorZ.setText("Escolher cor da peça Z");
        btChooseColorZ.setMaximumSize(new java.awt.Dimension(25, 23));
        btChooseColorZ.setMinimumSize(new java.awt.Dimension(25, 23));
        btChooseColorZ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btChooseColorZActionPerformed(evt);
            }
        });
        getContentPane().add(btChooseColorZ);

        btJogar.setText("Jogar");
        btJogar.setMaximumSize(new java.awt.Dimension(25, 23));
        btJogar.setMinimumSize(new java.awt.Dimension(25, 23));
        btJogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btJogarActionPerformed(evt);
            }
        });
        getContentPane().add(btJogar);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        setExtendedState(MAXIMIZED_BOTH);
    }//GEN-LAST:event_formWindowOpened

    private void btChooseColorIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btChooseColorIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btChooseColorIActionPerformed

    private void btChooseColorJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btChooseColorJActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btChooseColorJActionPerformed

    private void btChooseColorLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btChooseColorLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btChooseColorLActionPerformed

    private void btChooseColorOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btChooseColorOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btChooseColorOActionPerformed

    private void btChooseColorTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btChooseColorTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btChooseColorTActionPerformed

    private void btChooseColorSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btChooseColorSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btChooseColorSActionPerformed

    private void btChooseColorZActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btChooseColorZActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btChooseColorZActionPerformed

    private void btJogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btJogarActionPerformed
        // TODO add your handling code here:
        GraphicsTetrisDialog g = new GraphicsTetrisDialog(this, true);
       g.tetrisGame1.colors = colors;
        g.show();
        dispose();
    }//GEN-LAST:event_btJogarActionPerformed

    @Override
    public void actionPerformed(ActionEvent e) {

        if (e.getSource() == btChooseColorI) {
            chosenColorPieceI = JColorChooser.showDialog(null,
                    "escolher cor peça I",
                    Color.BLACK);
            colors.setIColor(chosenColorPieceI);

        }
        if (e.getSource() == btChooseColorJ) {
            chosenColorPieceJ = JColorChooser.showDialog(null,
                    "escolher cor peça j",
                    Color.BLACK);
            colors.setJColor(chosenColorPieceJ);

        }

        if (e.getSource() == btChooseColorL) {
            chosenColorPieceL = JColorChooser.showDialog(null,
                    "escolher cor peça L",
                    Color.BLACK);
            colors.setLColor(chosenColorPieceL);
        }

        if (e.getSource() == btChooseColorO) {
            chosenColorPieceO = JColorChooser.showDialog(null,
                    "escolher cor peça O",
                    Color.BLACK);
            colors.setOColor(chosenColorPieceO);

        }

        if (e.getSource() == btChooseColorT) {
            chosenColorPieceT = JColorChooser.showDialog(null,
                    "escolher cor peça T",
                    Color.BLACK);
            colors.setTColor(chosenColorPieceT);
        }

        if (e.getSource() == btChooseColorS) {
            chosenColorPieceS = JColorChooser.showDialog(null,
                    "escolher cor peça S",
                    Color.BLACK);
            colors.setSColor(chosenColorPieceS);

        }

        if (e.getSource() == btChooseColorZ) {
            chosenColorPieceZ = JColorChooser.showDialog(null,
                    "escolher cor peça Z",
                    Color.BLACK);
            colors.setZColor(chosenColorPieceZ);

        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info
                    : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cores.class.getName()).log(
                    java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cores.class.getName()).log(
                    java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cores.class.getName()).log(
                    java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cores.class.getName()).log(
                    java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btChooseColorI;
    private javax.swing.JButton btChooseColorJ;
    private javax.swing.JButton btChooseColorL;
    private javax.swing.JButton btChooseColorO;
    private javax.swing.JButton btChooseColorS;
    private javax.swing.JButton btChooseColorT;
    private javax.swing.JButton btChooseColorZ;
    private javax.swing.JButton btJogar;
    // End of variables declaration//GEN-END:variables

}
