/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package tetris.app;

import java.awt.event.KeyEvent;
import javax.swing.JButton;

/**
 *
 * @author IPT
 */
public class GraphicsTetrisDialog extends javax.swing.JDialog {

    /**
     * Creates new form TextTetrisDialog
     */
    public GraphicsTetrisDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jBPause = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        board = new tetris.lib.board.TetrisGame();
        jPanel8 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocationByPlatform(true);
        setMaximumSize(new java.awt.Dimension(1525, 820));
        setMinimumSize(new java.awt.Dimension(1525, 820));
        setPreferredSize(new java.awt.Dimension(1525, 820));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        jPanel6.setBackground(new java.awt.Color(102, 204, 255));
        jPanel6.setLayout(new java.awt.GridLayout(1, 0, 40, 20));

        jPanel9.setBackground(new java.awt.Color(102, 204, 255));
        jPanel9.setLayout(new java.awt.BorderLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tetris/resources/Design sem nome - Copy.png"))); // NOI18N
        jPanel9.add(jLabel1, java.awt.BorderLayout.CENTER);

        jBPause.setFont(new java.awt.Font("League Spartan Thin", 1, 48)); // NOI18N
        jBPause.setForeground(new java.awt.Color(102, 204, 255));
        jBPause.setText("Pause");
        jBPause.setBorder(null);
        jBPause.setBorderPainted(false);
        jBPause.setPreferredSize(new java.awt.Dimension(119, 70));
        jBPause.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                jBPauseInputMethodTextChanged(evt);
            }
        });
        jBPause.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPauseActionPerformed(evt);
            }
        });
        jPanel9.add(jBPause, java.awt.BorderLayout.PAGE_START);

        jPanel6.add(jPanel9);

        jPanel1.setBackground(new java.awt.Color(102, 204, 255));
        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        board.setBackground(new java.awt.Color(102, 204, 255));
        board.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                boardKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout boardLayout = new javax.swing.GroupLayout(board);
        board.setLayout(boardLayout);
        boardLayout.setHorizontalGroup(
            boardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 652, Short.MAX_VALUE)
        );
        boardLayout.setVerticalGroup(
            boardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1600, Short.MAX_VALUE)
        );

        jPanel1.add(board);

        jPanel6.add(jPanel1);

        jPanel8.setBackground(new java.awt.Color(102, 204, 255));
        jPanel8.setLayout(new java.awt.GridLayout(1, 0));

        jLabel2.setBackground(new java.awt.Color(102, 204, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tetris/resources/Design sem nome - Copy.png"))); // NOI18N
        jPanel8.add(jLabel2);

        jPanel6.add(jPanel8);

        getContentPane().add(jPanel6);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boardKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_boardKeyPressed
        if (board.getIsGamePaused() == false) {
            switch (evt.getKeyCode()) {
                case KeyEvent.VK_LEFT -> board.moveLeft();
                case KeyEvent.VK_RIGHT -> board.moveRight();
                case KeyEvent.VK_DOWN -> {
                    board.fallDown();
                    if (board.getCanSkipPiece() == false) {
                        board.setCanSkipPiece(true);
                    }
                }
                case KeyEvent.VK_UP -> board.rotate();
                case KeyEvent.VK_SPACE -> board.skipPiece();
                case KeyEvent.VK_ENTER -> board.pauseOrUnpauseGame();
                default -> {
                }
            }

        } else {
            if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
                board.pauseOrUnpauseGame();
            }
        }
    }//GEN-LAST:event_boardKeyPressed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

    }//GEN-LAST:event_formWindowOpened

    private void jBPauseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPauseActionPerformed
        if (((String)evt.getActionCommand()).equals("Pause")){
            jBPause.setText("Play");
            board.pauseOrUnpauseGame();
        }else{
            jBPause.setText("Pause");
        }
        if (((String)evt.getActionCommand()).equals("Play")){
            jBPause.setText("Pause");
            board.pauseOrUnpauseGame();
        }else{
            jBPause.setText("Play");
        }
    }//GEN-LAST:event_jBPauseActionPerformed

    private void jBPauseInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jBPauseInputMethodTextChanged

    }//GEN-LAST:event_jBPauseInputMethodTextChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info
                    : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GraphicsTetrisDialog.class.
                    getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GraphicsTetrisDialog.class.
                    getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GraphicsTetrisDialog.class.
                    getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GraphicsTetrisDialog.class.
                    getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GraphicsTetrisDialog dialog = new GraphicsTetrisDialog(
                        new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private tetris.lib.board.TetrisGame board;
    private javax.swing.JButton jBPause;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    // End of variables declaration//GEN-END:variables
}
