/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tetris.app;

/**
 *
 * @author Bea⚝
 */
public class Rules extends javax.swing.JFrame {

    /**
     * Creates new form Rules
     */
    public Rules() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPRules = new javax.swing.JPanel();
        jPLR = new javax.swing.JPanel();
        jPLR1 = new javax.swing.JPanel();
        jLR = new javax.swing.JLabel();
        jPLR2 = new javax.swing.JPanel();
        jPR1 = new javax.swing.JPanel();
        jPR2 = new javax.swing.JPanel();
        jPV = new javax.swing.JPanel();
        jP1 = new javax.swing.JPanel();
        jPbt = new javax.swing.JPanel();
        jPbt1 = new javax.swing.JPanel();
        btVoltar = new javax.swing.JButton();
        jPbt2 = new javax.swing.JPanel();
        jP2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        jPRules.setBackground(new java.awt.Color(102, 204, 255));
        jPRules.setLayout(new java.awt.GridLayout(4, 0));

        jPLR.setBackground(new java.awt.Color(102, 204, 255));
        jPLR.setLayout(new java.awt.GridLayout(1, 0));

        jPLR1.setBackground(new java.awt.Color(102, 204, 255));

        javax.swing.GroupLayout jPLR1Layout = new javax.swing.GroupLayout(jPLR1);
        jPLR1.setLayout(jPLR1Layout);
        jPLR1Layout.setHorizontalGroup(
            jPLR1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 246, Short.MAX_VALUE)
        );
        jPLR1Layout.setVerticalGroup(
            jPLR1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 147, Short.MAX_VALUE)
        );

        jPLR.add(jPLR1);

        jLR.setFont(new java.awt.Font("League Spartan Thin", 1, 60)); // NOI18N
        jLR.setForeground(new java.awt.Color(255, 255, 255));
        jLR.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLR.setText("Regras");
        jPLR.add(jLR);

        jPLR2.setBackground(new java.awt.Color(102, 204, 255));

        javax.swing.GroupLayout jPLR2Layout = new javax.swing.GroupLayout(jPLR2);
        jPLR2.setLayout(jPLR2Layout);
        jPLR2Layout.setHorizontalGroup(
            jPLR2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 246, Short.MAX_VALUE)
        );
        jPLR2Layout.setVerticalGroup(
            jPLR2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 147, Short.MAX_VALUE)
        );

        jPLR.add(jPLR2);

        jPRules.add(jPLR);

        javax.swing.GroupLayout jPR1Layout = new javax.swing.GroupLayout(jPR1);
        jPR1.setLayout(jPR1Layout);
        jPR1Layout.setHorizontalGroup(
            jPR1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 739, Short.MAX_VALUE)
        );
        jPR1Layout.setVerticalGroup(
            jPR1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 147, Short.MAX_VALUE)
        );

        jPRules.add(jPR1);

        javax.swing.GroupLayout jPR2Layout = new javax.swing.GroupLayout(jPR2);
        jPR2.setLayout(jPR2Layout);
        jPR2Layout.setHorizontalGroup(
            jPR2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 739, Short.MAX_VALUE)
        );
        jPR2Layout.setVerticalGroup(
            jPR2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 147, Short.MAX_VALUE)
        );

        jPRules.add(jPR2);

        jPV.setLayout(new java.awt.GridLayout(1, 3));

        jP1.setBackground(new java.awt.Color(102, 204, 255));

        javax.swing.GroupLayout jP1Layout = new javax.swing.GroupLayout(jP1);
        jP1.setLayout(jP1Layout);
        jP1Layout.setHorizontalGroup(
            jP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 246, Short.MAX_VALUE)
        );
        jP1Layout.setVerticalGroup(
            jP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 147, Short.MAX_VALUE)
        );

        jPV.add(jP1);

        jPbt.setBackground(new java.awt.Color(102, 204, 255));
        jPbt.setLayout(new java.awt.GridLayout(3, 0));

        jPbt1.setBackground(new java.awt.Color(102, 204, 255));

        javax.swing.GroupLayout jPbt1Layout = new javax.swing.GroupLayout(jPbt1);
        jPbt1.setLayout(jPbt1Layout);
        jPbt1Layout.setHorizontalGroup(
            jPbt1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 246, Short.MAX_VALUE)
        );
        jPbt1Layout.setVerticalGroup(
            jPbt1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 49, Short.MAX_VALUE)
        );

        jPbt.add(jPbt1);

        btVoltar.setFont(new java.awt.Font("League Spartan Thin", 1, 48)); // NOI18N
        btVoltar.setForeground(new java.awt.Color(102, 204, 255));
        btVoltar.setText("Voltar");
        btVoltar.setBorder(null);
        btVoltar.setBorderPainted(false);
        btVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltarActionPerformed(evt);
            }
        });
        jPbt.add(btVoltar);

        jPbt2.setBackground(new java.awt.Color(102, 204, 255));

        javax.swing.GroupLayout jPbt2Layout = new javax.swing.GroupLayout(jPbt2);
        jPbt2.setLayout(jPbt2Layout);
        jPbt2Layout.setHorizontalGroup(
            jPbt2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 246, Short.MAX_VALUE)
        );
        jPbt2Layout.setVerticalGroup(
            jPbt2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 49, Short.MAX_VALUE)
        );

        jPbt.add(jPbt2);

        jPV.add(jPbt);

        jP2.setBackground(new java.awt.Color(102, 204, 255));

        javax.swing.GroupLayout jP2Layout = new javax.swing.GroupLayout(jP2);
        jP2.setLayout(jP2Layout);
        jP2Layout.setHorizontalGroup(
            jP2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 246, Short.MAX_VALUE)
        );
        jP2Layout.setVerticalGroup(
            jP2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 147, Short.MAX_VALUE)
        );

        jPV.add(jP2);

        jPRules.add(jPV);

        getContentPane().add(jPRules);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltarActionPerformed
        Inicial i = new Inicial();
        i.show();
        dispose();
    }//GEN-LAST:event_btVoltarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        setExtendedState(MAXIMIZED_BOTH);
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Rules.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Rules.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Rules.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Rules.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Rules().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btVoltar;
    private javax.swing.JLabel jLR;
    private javax.swing.JPanel jP1;
    private javax.swing.JPanel jP2;
    private javax.swing.JPanel jPLR;
    private javax.swing.JPanel jPLR1;
    private javax.swing.JPanel jPLR2;
    private javax.swing.JPanel jPR1;
    private javax.swing.JPanel jPR2;
    private javax.swing.JPanel jPRules;
    private javax.swing.JPanel jPV;
    private javax.swing.JPanel jPbt;
    private javax.swing.JPanel jPbt1;
    private javax.swing.JPanel jPbt2;
    // End of variables declaration//GEN-END:variables
}
